# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./QtGuiApplication1.h \
    $$PWD/../../../../../Qt/Qt5.12.9/5.12.9/msvc2017_64/include/QtSerialPort/qserialport.h \
    $$PWD/../../../../../Qt/Qt5.12.9/5.12.9/msvc2017_64/include/QtSerialPort/qserialportinfo.h \
    $$PWD/../../../../../Qt/Qt5.12.9/5.12.9/msvc2017_64/include/QtWebEngineWidgets/qwebenginepage.h \
    $$PWD/../../../../../Qt/Qt5.12.9/5.12.9/msvc2017_64/include/QtWebEngineWidgets/qwebengineview.h \
    $$PWD/../../../../../Qt/Qt5.12.9/Examples/Qt-5.12.9/webchannel/shared/websocketclientwrapper.h \
    $$PWD/../../../../../Qt/Qt5.12.9/Examples/Qt-5.12.9/webchannel/shared/websockettransport.h \
    ./x64/Debug/uic/ui_QtGuiApplication1.h
SOURCES += ./main.cpp \
    $$PWD/../../../../../Qt/Qt5.12.9/Examples/Qt-5.12.9/webchannel/shared/websocketclientwrapper.cpp \
    $$PWD/../../../../../Qt/Qt5.12.9/Examples/Qt-5.12.9/webchannel/shared/websockettransport.cpp \
    ./QtGuiApplication1.cpp
FORMS += ./QtGuiApplication1.ui
RESOURCES += QtGuiApplication1.qrc
